### ISSUE TITLE
aridityIndexThornthwaite and assignNames issue

### ISSUE THREAD

**Issue by PabloCSZ** [ptitle/envirem#4]
Hi,

I dont know if it is only in my case but I think there is a mistake in the aridityIndexThornthwaite function. 

All available examples and tutorial suggest that the layers of the Precipitation rasterstack object have to be named "prec_##". However, I tried it and the function didn't work.

After checking your source code, I noticed that the layers must be named "precip_##" instead. and that fixed the issue. 

I re-named the layers with base R instead of assignNames because that function didn't work out. Not sure where is the problem anymore

**Comment by ptitle** [comment]
Hi,
Perhaps this could be better explained in the documentation, but you need to use the assignNames() function in order to tell the envirem functions how your rasters are named. So, for example, if your monthly precip rasters are named "rain_01_worldclim" for january precipitation, then you would use the assignNames() function to specify:

`assignNames(precip = "rain_##_worldclim")`

The `##` is meant as a placeholder, representing the month numbering, and is not meant to actually be in the raster names. 

Does that make sense? Let me know if that solves the problem. And feel free to post code and errors here to help me help you.

-Pascal

**Comment by PabloCSZ** [comment]
Hi, 

Thanks for the quick response. I noticed that assignNames() was definitely the problem for me. 
So, it took me a lot of time to realize how assignNames is suposed to work. 

I thought "precip" was the name of the rasterbrick, I was running something like:

assignNames(myrasterbirck = "precip_##")

Everything is clear to me now, thanks for your help.
