### ISSUE TITLE
calculate mean temp of the coldest month using generateRasters()?

### ISSUE THREAD

**Issue by mariaemilyd** [ptitle/envirem#5]
Hi Pascal,

Thanks for the great package and the nice tutorial vignette.

I was just wondering if it would be possible to add mean temp of the coldest month as a variable to the generateRasters() function? maxTempColdest is an option at the moment. 

I can see you can calculate mean temp coldest month using the function otherTempExtremes() but I would like to be able to calculate it without loading raster stacks into R,  to reduce the computational load.

Thanks,

Maria

**Comment by mariaemilyd** [comment]
Also, from your tutorial, can you clarify why you use solar radiation in one method to calculate GDD  [gdd <- layerCreation(chelsaStack, solarStack, var = 'growingDegDays5')] but not the other [gdd <- growingDegDays(meantempstack, baseTemp = 5)]?  I've checked out the source paper (Metzger et al 2012) but there is nothing about using solar radiation to calculate GDD there?

**Comment by ptitle** [comment]
Hi Maria,
I've added mean temp coldest month and mean temp warmest month, as you requested. Please update your version to the github version. 
As for your other question, solar radiation is never used for GDD. This is just an artifact since in the layerCreation function, it checks that all input rasters have been properly provided (temp, precip, solar radiation), regardless of whether or not you are only requesting specific variables.

**Comment by ptitle** [comment]
I went ahead and made some adjustments such that now if the variables you request with layerCreation() or generateRasters() don't need solar radiation as inputs, then solar radiation rasters are not expected in the inputs. Thanks for pointing out these issues!
